package testutils

import (
	"io"
	"net/http"
	"net/http/httptest"
)

// ExecuteTestRequest runs a request using the given router, and returns the response recorder
func ExecuteTestRequest(router http.Handler, method, url string, body io.Reader) *httptest.ResponseRecorder {
	response := httptest.NewRecorder()
	request, _ := http.NewRequest(method, url, body)

	router.ServeHTTP(response, request)

	return response
}

// FloatSlice takes a range and a resolution, and returns the coordinates generated by it
func FloatSlice(from, to float64, resolution int) []float64 {
	numSamples := int(to-from+1) * resolution
	result := make([]float64, 0, numSamples)
	for lattice := from; lattice < to; lattice++ {
		for res := 0; res < resolution; res++ {
			result = append(result, lattice+float64(res)/float64(resolution))
		}
	}
	return result
}
